export default function PrivacyPage() {
  return (
    <div className="container mx-auto px-4 py-12">
      <div className="max-w-4xl mx-auto bg-white/80 backdrop-blur-sm rounded-2xl p-8 border-2 border-gray-200">
        <h1 className="text-4xl font-bold mb-6 text-gray-800">Privacy Policy</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: January 2025</p>

        <div className="prose prose-gray max-w-none">
          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-800">1. Introduction</h2>
            <p className="text-gray-700 mb-4">
              IJBoba 606 (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our web application.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-800">2. Information We Collect</h2>
            <h3 className="text-xl font-semibold mb-3 text-gray-800">2.1 Account Information</h3>
            <ul className="list-disc list-inside mb-4 text-gray-700 space-y-2">
              <li>When you sign in with Google: Your email address, name, and profile picture</li>
              <li>When you use as guest: Anonymous user ID generated by Firebase</li>
              <li>User handle (username) created during account setup</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3 text-gray-800">2.2 Usage Data</h3>
            <ul className="list-disc list-inside mb-4 text-gray-700 space-y-2">
              <li>Quiz performance: Scores, levels completed, badges earned</li>
              <li>Streak data: Days played, last played date (Africa/Lagos timezone)</li>
              <li>Forum activity: Posts, threads, votes, subscriptions</li>
              <li>Calculator data: Tax calculations you save to your profile</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3 text-gray-800">2.3 Technical Data</h3>
            <ul className="list-disc list-inside mb-4 text-gray-700 space-y-2">
              <li>Browser type and version</li>
              <li>Device information</li>
              <li>IP address (stored by Firebase)</li>
              <li>Usage patterns and interactions</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-800">3. How We Use Your Information</h2>
            <ul className="list-disc list-inside mb-4 text-gray-700 space-y-2">
              <li>To provide and maintain our service</li>
              <li>To track your progress (quizzes, badges, streaks)</li>
              <li>To enable forum participation and community features</li>
              <li>To save your calculator results (if you choose to save them)</li>
              <li>To display leaderboards (anonymized or with your chosen handle)</li>
              <li>To send notifications about forum activity (replies, mentions, etc.)</li>
              <li>To improve our service and user experience</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-800">4. Data Sharing and Disclosure</h2>
            <p className="text-gray-700 mb-4">
              We do NOT sell your personal information. We may share data only in these limited circumstances:
            </p>
            <ul className="list-disc list-inside mb-4 text-gray-700 space-y-2">
              <li><strong>Public leaderboards:</strong> Your handle and scores (if leaderboards are enabled)</li>
              <li><strong>Forum posts:</strong> Your handle and content you post publicly</li>
              <li><strong>Service providers:</strong> Firebase/Google Cloud (for hosting and authentication)</li>
              <li><strong>Legal requirements:</strong> If required by law or to protect our rights</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-800">5. Data Security</h2>
            <p className="text-gray-700 mb-4">
              We use Firebase security rules and authentication to protect your data. However, no method of transmission over the Internet is 100% secure. We strive to use commercially acceptable means to protect your personal information.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-800">6. Your Rights</h2>
            <p className="text-gray-700 mb-4">You have the right to:</p>
            <ul className="list-disc list-inside mb-4 text-gray-700 space-y-2">
              <li>Access your personal data</li>
              <li>Correct inaccurate data</li>
              <li>Delete your account and data</li>
              <li>Export your data</li>
              <li>Opt out of leaderboards</li>
            </ul>
            <p className="text-gray-700 mb-4">
              To exercise these rights, please contact us (contact information in footer).
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-800">7. Cookies and Tracking</h2>
            <p className="text-gray-700 mb-4">
              We use Firebase Authentication which uses cookies and local storage to maintain your session. We do not use third-party advertising or tracking cookies.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-800">8. Children&apos;s Privacy</h2>
            <p className="text-gray-700 mb-4">
              Our service is not directed to children under 13. If you believe a child under 13 has provided us with personal information, please contact us.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-800">9. Changes to This Policy</h2>
            <p className="text-gray-700 mb-4">
              We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new policy on this page and updating the &quot;Last updated&quot; date.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-800">10. Contact Us</h2>
            <p className="text-gray-700 mb-4">
              If you have questions about this Privacy Policy, please contact us through the footer links or GitHub repository.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}


